version: '3.4'

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
      POSTGRES_DB: {{ cookiecutter.project_slug }}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: sh -c 'while true; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done'
    environment:
      ALLOWED_HOSTS: >-
        localhost
      DATABASE_URL: postgresql://postgres@db/{{ cookiecutter.project_slug }}
    ports:
      - 8000
    volumes:
      - venv:/venv
      - .:/code
    depends_on:
      - db
    stdin_open: true
    tty: true
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    command: npm start
    volumes:
      - .:/code
    ports:
      - 3000
volumes:
  pgdata:
  venv:
